export enum ApiCodes {
  // Auth
  TOKEN_EXPIRED = 'TOKEN_EXPIRED',
  INVALID_TOKEN = 'INVALID_TOKEN',
  TOKEN_FORBIDDEN = 'TOKEN_FORBIDDEN',
  ONBOARDING_PROCESS_MISSING = 'ONBOARDING_PROCESS_MISSING',

  // General
  ENTITY_NOT_FOUND = 'ENTITY_NOT_FOUND',
}
